; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Spacefall_gameplay:

.export _music_data_spacefall_gameplay:=music_data_spacefall_gameplay

music_data_spacefall_gameplay:
	.byte 3
	.word @instruments
	.word @samples-4
; 00 : 00_Title
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : 01_Gameplay
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : 02_Boss
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_spacefall_gameplay
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env4,@env7,@env5 ; 00 : Instrument 5
	.word @env3,@env4,@env8,@env5 ; 01 : Instrument 4
	.word @env6,@env4,@env7,@env0 ; 02 : Noise_CosmicHiss
	.word @env2,@env4,@env8,@env0 ; 03 : Instrument 1
	.word @env9,@env4,@env8,@env10 ; 04 : Instrument 2
	.word @env3,@env4,@env7,@env0 ; 05 : Instrument 3

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$00,$07
@env2:
	.byte $00,$c3,$7f,$00,$02
@env3:
	.byte $00,$ca,$7f,$00,$02
@env4:
	.byte $c0,$7f,$00,$01
@env5:
	.byte $00,$c0,$c0,$bf,$c0,$c1,$c0,$bf,$c0,$00,$08
@env6:
	.byte $00,$c7,$c3,$c0,$00,$03
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $c1,$7f,$00,$00
@env9:
	.byte $00,$c1,$7f,$00,$02
@env10:
	.byte $00,$c0,$bf,$c1,$bf,$c1,$bf,$c1,$c0,$00,$08

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $bf, $48, $ff, $a1, $80, $1b, $ff, $9b, $48, $00
	.byte $ff, $ff, $bd, $48, $ff, $9f, $1b, $ff, $9d, $48, $00, $ff, $e9, $1e, $cd, $00, $81, $48, $ff, $a1, $1d, $ff, $9b, $48
	.byte $00, $ff, $ed, $1b, $cd, $48, $00, $ff, $9d, $16, $ff, $9d, $48, $00, $ff, $ed, $1e, $cd, $48, $00, $ff, $ff, $bd, $48
	.byte $ff, $9f, $20, $cd, $00, $cd, $48, $ff, $9f, $1b, $ff, $9d, $48, $00, $ff, $ff, $bd, $48, $ff, $ef, $1d, $c9, $00, $81
	.byte $48, $ff, $9f, $16, $f5, $00, $a5, $48, $ff, $ff, $bf, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $ff, $a1, $82, $22, $ff, $9b, $27, $ff, $e9, $00, $d1, $cf, $2a, $ff, $9d, $29, $cd, $27, $ff, $ff, $b9, $00, $81, $d1
	.byte $2a, $ff, $9b, $00, $cd, $81, $29, $ff, $ed, $00, $cb, $d3, $27, $ff, $9b, $25, $cb, $81, $22, $ff, $ff, $bb, $00, $ff
	.byte $ed, $2a, $cd, $00, $ff, $9d, $29, $ff, $9d, $00, $cf, $2c, $ff, $9b, $2a, $cd, $27, $ff, $ff, $bd, $2a, $ff, $ff, $bd
	.byte $29, $ff, $ff, $bd, $00, $27, $ff, $ff, $bb, $22, $ff, $ff, $95, $00, $a5, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $8a, $0f, $ff, $ff, $bd, $ff, $ff, $bf, $0d, $ff, $ff, $bd, $0f, $ff, $ff, $bd, $00, $0b, $ff, $ff, $bb, $0d, $ff, $ff
	.byte $bd, $00, $0f, $ff, $ff, $bb, $81, $0a, $ff, $ff, $bb, $0f, $ff, $ff, $bd, $0b, $ff, $ff, $bd, $08, $ff, $ff, $bd, $0f
	.byte $ff, $ff, $bd, $80, $0b, $ff, $ff, $bd, $0a, $ff, $ff, $bd, $0f, $ff, $ff, $bd, $0f, $ff, $ff, $97, $00, $a3, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $f1, $84, $0f, $cb, $00, $ff, $ff, $bd, $cf, $0f, $cd, $00, $ff, $9d, $ff, $ff, $bf
	.byte $ff, $ef, $0f, $cd, $0f, $cd, $00, $ff, $ed, $ff, $ff, $bf, $ff, $ef, $0f, $cd, $00, $ff, $ff, $bd
@song0ref313:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $0f
	.word @song0ref313
	.byte $41, $0f
	.word @song0ref313
	.byte $41, $0f
	.word @song0ref313
	.byte $ff, $ff, $bf, $42
	.word @song0ch4loop
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $86
@song1ref6:
	.byte $2a, $99, $2e, $8b, $31, $81, $33, $87, $29, $99, $00, $99
	.byte $41, $0c
	.word @song1ref6
	.byte $48
	.byte $41, $0c
	.word @song1ref6
	.byte $41, $0c
	.word @song1ref6
@song1ref28:
	.byte $48
@song1ref29:
	.byte $2a, $99, $2e, $8b, $31, $81, $35, $87, $29, $99, $00, $99
	.byte $41, $0c
	.word @song1ref29
	.byte $41, $0c
	.word @song1ref28
	.byte $2a, $99, $2e, $8b, $31, $81, $00, $35, $85, $29, $99, $00, $99, $48
@song1ref61:
	.byte $2a, $99, $2c, $8b, $30, $81, $33, $87, $29, $99, $00, $99
	.byte $41, $0c
	.word @song1ref61
	.byte $48, $2a, $99, $00, $99, $30, $99, $00, $99, $2a, $99, $00, $99, $30, $99, $00, $99, $48
@song1ref94:
	.byte $2a, $99, $35, $8b, $31, $81, $2e, $87, $29, $99, $00, $99
	.byte $41, $0c
	.word @song1ref94
	.byte $48, $2a, $99, $00, $ff, $c1, $48, $2a, $99
@song1ref118:
	.byte $33
@song1ref119:
	.byte $81, $00, $87, $33
@song1ref123:
	.byte $81, $00, $87, $29, $99, $00, $99, $2a, $99, $33, $83, $00, $85, $33, $81, $00, $87, $31, $99, $00, $99, $48, $2a, $99
	.byte $36, $83, $00, $85, $36
@song1ref152:
	.byte $83, $00, $85, $29, $99, $00, $99, $2a, $99, $38, $81, $00, $87, $38, $81, $00, $87, $29, $99, $00, $99, $48, $2a, $8b
	.byte $29, $8b, $2a, $8b, $29, $8b, $2a, $8b, $29, $8b, $2a, $8b, $29, $8b, $2a, $99, $00, $99, $29, $99, $00, $99, $48, $2a
	.byte $99, $2e, $83, $00, $85, $2e
	.byte $41, $09
	.word @song1ref123
	.byte $2e, $83, $00, $85, $2e
@song1ref214:
	.byte $83, $00, $85, $29, $99, $00, $99, $48, $2a, $99, $30, $83, $00, $85, $30
	.byte $41, $09
	.word @song1ref152
	.byte $30, $83, $00, $85, $30
	.byte $41, $09
	.word @song1ref214
	.byte $31, $83, $00, $85, $31
	.byte $41, $09
	.word @song1ref123
	.byte $31, $83, $00, $85, $31
	.byte $41, $09
	.word @song1ref214
	.byte $41, $0f
	.word @song1ref118
	.byte $41, $0b
	.word @song1ref119
	.byte $48, $2a, $99, $33, $83, $00, $85, $33
	.byte $41, $09
	.word @song1ref152
	.byte $33, $83, $00, $85, $33, $83, $00, $85, $29, $99, $00, $99, $42
	.word @song1ch0loop
@song1ch4:
@song1ch3:
@song1ch1:
@song1ch1loop:
@song1ref291:
	.byte $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df
	.byte $41, $0a
	.word @song1ref291
	.byte $41, $0a
	.word @song1ref291
	.byte $ff, $df, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $88, $0f, $b5, $00, $b5, $16, $b1, $00, $b9
@song1ref322:
	.byte $0f, $b5, $00, $b5
@song1ref326:
	.byte $16, $b5, $00, $b5, $0f, $b5, $00, $b5, $16, $b5, $00, $b5
	.byte $41, $10
	.word @song1ref322
	.byte $0f, $b1, $00, $b9
	.byte $41, $0c
	.word @song1ref326
	.byte $41, $10
	.word @song1ref322
	.byte $41, $10
	.word @song1ref322
	.byte $41, $10
	.word @song1ref322
	.byte $41, $10
	.word @song1ref322
	.byte $0f, $b5, $00, $b5, $16, $b5, $00, $b5, $42
	.word @song1ch2loop
@song2ch0:
@song2ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $86
@song2ref6:
	.byte $2e, $99, $00, $99, $31, $99, $00
@song2ref13:
	.byte $99, $33, $b5, $00, $b5, $48
@song2ref19:
	.byte $2e, $99, $00, $99, $30, $99, $00, $99, $31, $b5, $00, $b5, $48
@song2ref32:
	.byte $33, $b5, $00, $97, $31, $9b, $30, $99, $00, $99, $2e, $b5, $48
@song2ref45:
	.byte $35, $99, $00, $99, $35, $99, $00, $99, $35, $b5, $00, $b5, $48, $81
	.byte $41, $0b
	.word @song2ref6
	.byte $b3, $48, $81
	.byte $41, $0b
	.word @song2ref19
	.byte $b3, $48, $81
	.byte $41, $0b
	.word @song2ref32
	.byte $b3, $48, $81
	.byte $41, $0b
	.word @song2ref45
	.byte $b3, $48, $33, $99, $35, $99, $36, $99, $35
	.byte $41, $09
	.word @song2ref13
	.byte $31, $99, $00, $99, $33, $b5, $31, $b5, $48, $30, $99, $31, $99, $33, $99, $35, $99, $36, $b5, $00, $b5, $48, $35, $ed
	.byte $00, $ed, $48
	.byte $41, $30
	.word @song2ref6
	.byte $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $82
@song2ref127:
	.byte $1b, $99, $22, $99, $1b, $97, $00, $19, $99, $1b, $99, $22, $99, $1b, $97, $00, $1d, $99
	.byte $41, $0e
	.word @song2ref127
	.byte $99, $1d, $99
	.byte $41, $12
	.word @song2ref127
	.byte $41, $12
	.word @song2ref127
@song2ref157:
	.byte $1b, $99, $22, $99, $1b, $99, $19, $99, $1b, $99, $22, $99, $1e, $99, $1d, $99
	.byte $41, $10
	.word @song2ref157
	.byte $41, $10
	.word @song2ref157
	.byte $41, $10
	.word @song2ref157
	.byte $1b, $99, $22, $99, $19, $99, $1d, $99, $1b, $99, $22, $99, $24, $97, $00, $81
@song2ref198:
	.byte $19, $97, $1b, $97, $00, $22, $97, $00, $19, $97, $00, $1d, $97, $00, $1b, $97, $00, $22, $97, $00, $24, $95, $00, $83
	.byte $41, $18
	.word @song2ref198
	.byte $41, $18
	.word @song2ref198
	.byte $19, $97
@song2ref230:
	.byte $1b, $99, $00, $22, $97, $1b, $99, $19, $99, $1b, $99, $22, $99, $1b, $99, $00, $99
	.byte $41, $11
	.word @song2ref230
	.byte $41, $11
	.word @song2ref230
	.byte $41, $11
	.word @song2ref230
	.byte $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $88, $0f, $b5, $0f, $b5, $0d, $b5, $0f
@song2ref268:
	.byte $b5, $0f
@song2ref270:
	.byte $b5, $12, $b5, $11, $b5, $0f, $b5, $0f, $b5, $0f, $b5, $0d, $b5, $0a
	.byte $41, $0b
	.word @song2ref268
@song2ref287:
	.byte $11, $b5, $12, $b5, $11, $b5, $0f, $b5, $0d, $b5, $0c, $b5, $0d, $b5, $0f, $b5, $0a, $b5, $0d, $b5, $0f, $b5, $11
	.byte $41, $09
	.word @song2ref270
	.byte $0d, $b5, $0f, $b5
	.byte $41, $12
	.word @song2ref287
	.byte $0f, $ff, $dd, $0f, $b5, $0d, $b5, $0a, $b5, $0f, $b5, $0f, $b5
	.byte $41, $0e
	.word @song2ref287
	.byte $0d, $ff, $db, $00, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $84
@song2ref345:
	.byte $27, $99, $27, $99, $27, $99, $27, $99, $27, $99
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $09
	.word @song2ref345
@song2ref391:
	.byte $8b, $27, $8b, $27, $8b, $27, $8b, $27, $8b, $27
	.byte $41, $0a
	.word @song2ref391
	.byte $41, $0a
	.word @song2ref391
	.byte $41, $0a
	.word @song2ref391
	.byte $41, $0a
	.word @song2ref391
	.byte $41, $0a
	.word @song2ref391
	.byte $41, $0a
	.word @song2ref391
	.byte $41, $0a
	.word @song2ref391
	.byte $41, $0a
	.word @song2ref391
	.byte $41, $0a
	.word @song2ref391
	.byte $41, $0a
	.word @song2ref391
	.byte $41, $0a
	.word @song2ref391
	.byte $8b, $27, $8b, $27, $8b, $27, $8b
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $41, $0a
	.word @song2ref345
	.byte $27, $99, $27, $99, $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
@song2ref467:
	.byte $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df
	.byte $41, $0a
	.word @song2ref467
	.byte $41, $0a
	.word @song2ref467
	.byte $ff, $df, $42
	.word @song2ch4loop
