; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_firing
	.word @sfx_ntsc_explosion

@sfx_ntsc_firing:
	.byte $84,$72,$85,$00,$83,$3a,$89,$f0,$01,$84,$86,$83,$38,$01,$84,$9a
	.byte $83,$35,$01,$84,$a5,$01,$84,$b9,$01,$84,$b7,$01,$84,$cb,$01,$84
	.byte $df,$01,$84,$f3,$01,$84,$07,$85,$01,$01,$84,$1b,$01,$84,$2f,$01
	.byte $00
@sfx_ntsc_explosion:
	.byte $8a,$0e,$89,$3f,$01,$89,$3a,$02,$89,$36,$02,$8a,$0f,$07,$00

.export sounds
